# projects paths arborescence
# should be all relative to project's root
# will be expanded to absolute paths by the code
# (this to avoid windows/linux path issues)
paths:
    src: ['src']
    config: ['config']
    outputs: ['outputs']
    dataset: ['data','toy']
    metadata: ['data', 'flair-1_metadata_aerial.json']
    # will contain list of img and mask files with metadata
    files_csv: ['data', 'toy','toydataset.csv']
    files_df: ['data', 'toy','toydataset.pkl']

image_extension: '.tif'

        
    


# this is from https://github.com/IGNF/FLAIR-1/blob/205aa15f48403709af46b0973ea8ae57b5d12eb0/configs/flair-1-config.yaml
# and https://github.com/IGNF/FLAIR-2/blob/b9b48922bf18c8e3dd93c2ce76120ec4ad40d741/notebook/data_display.py#L23


nomenclature:
  # voir https://arxiv.org/abs/2211.12979

  # remarque: ligneux et mixte ont des valeurs interverties entre le code de FAIR et dans la doc, 
  # mais ces classes ne sont pas distinguées dans les modèles de FAIR 
    channels:
        0: 'R'
        1: 'G'
        2: 'B'
        3: 'NIR'
        4: 'Elevation'
    classes:
        english:
            1  : 'building'
            2  : 'pervious surface'
            3  : 'impervious surface'
            4  : 'bare soil'
            5  : 'water'
            6  : 'coniferous'
            7  : 'deciduous'
            8  : 'brushwood'
            9  : 'vineyard'
            10 : 'herbaceous vegetation'
            11 : 'agricultural land'
            12 : 'plowed land'
            13 : 'swimming_pool'
            14 : 'snow'
            15 : 'clear cut'
            16 : 'mixed'
            17 : 'ligneous'
            18 : 'greenhouse'
            19 : 'other'
        french:
            1  : 'bâtiment'
            2  : 'surface perméable'
            3  : 'surface imperméable'
            4  : 'sol nu'
            5  : 'eau'
            6  : 'conifère'
            7  : 'feuillu'
            8  : 'buisson'
            9  : 'vignoble'
            10 : 'végétation herbacée'
            11 : 'terre agricole'
            12 : 'terre labourée'
            13 : 'piscine'
            14 : 'neige'
            15 : 'coupe claire'
            16 : 'mixte'
            17 : 'ligneux'
            18 : 'serre'
            19 : 'autre'
    artificiel: [1, 2, 3, 13, 18] # Anthropized surfaces without vegetation
    vegetal: [6, 7, 8, 9, 10, 11, 12, 15, 16, 17, ] # Vegetated surfaces
    
    # de https://github.com/IGNF/FLAIR-2/blob/b9b48922bf18c8e3dd93c2ce76120ec4ad40d741/notebook/data_display.py#L23
    colors:
        1   : '#db0e9a'
        2   : '#938e7b'
        3   : '#f80c00'
        4   : '#a97101'
        5   : '#1553ae'
        6   : '#194a26'
        7   : '#46e483'
        8   : '#f3a60d'
        9   : '#660082'
        10  : '#55ff00'
        11  : '#fff30d'
        12  : '#e4df7c'
        13  : '#3de6eb'
        14  : '#ffffff'
        15  : '#8ab3a0'
        16  : '#6b714f'
        17  : '#c5dc42'
        18  : '#9999ff'
        19  : '#000000'




